# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /ssd/1/wangyin.yx/tf_search_env_20191206/absl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /ssd/1/wangyin.yx/tf_search_env_20191206/absl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /ssd/1/wangyin.yx/tf_search_env_20191206/absl/CMakeFiles /ssd/1/wangyin.yx/tf_search_env_20191206/absl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /ssd/1/wangyin.yx/tf_search_env_20191206/absl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raw_logging_internal

# Build rule for target.
raw_logging_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raw_logging_internal
.PHONY : raw_logging_internal

# fast build rule for target.
raw_logging_internal/fast:
	$(MAKE) -f absl/base/CMakeFiles/raw_logging_internal.dir/build.make absl/base/CMakeFiles/raw_logging_internal.dir/build
.PHONY : raw_logging_internal/fast

#=============================================================================
# Target rules for targets named spinlock_wait

# Build rule for target.
spinlock_wait: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spinlock_wait
.PHONY : spinlock_wait

# fast build rule for target.
spinlock_wait/fast:
	$(MAKE) -f absl/base/CMakeFiles/spinlock_wait.dir/build.make absl/base/CMakeFiles/spinlock_wait.dir/build
.PHONY : spinlock_wait/fast

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f absl/base/CMakeFiles/base.dir/build.make absl/base/CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named dynamic_annotations

# Build rule for target.
dynamic_annotations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamic_annotations
.PHONY : dynamic_annotations

# fast build rule for target.
dynamic_annotations/fast:
	$(MAKE) -f absl/base/CMakeFiles/dynamic_annotations.dir/build.make absl/base/CMakeFiles/dynamic_annotations.dir/build
.PHONY : dynamic_annotations/fast

#=============================================================================
# Target rules for targets named malloc_internal

# Build rule for target.
malloc_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 malloc_internal
.PHONY : malloc_internal

# fast build rule for target.
malloc_internal/fast:
	$(MAKE) -f absl/base/CMakeFiles/malloc_internal.dir/build.make absl/base/CMakeFiles/malloc_internal.dir/build
.PHONY : malloc_internal/fast

#=============================================================================
# Target rules for targets named throw_delegate

# Build rule for target.
throw_delegate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 throw_delegate
.PHONY : throw_delegate

# fast build rule for target.
throw_delegate/fast:
	$(MAKE) -f absl/base/CMakeFiles/throw_delegate.dir/build.make absl/base/CMakeFiles/throw_delegate.dir/build
.PHONY : throw_delegate/fast

#=============================================================================
# Target rules for targets named raw_hash_set

# Build rule for target.
raw_hash_set: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raw_hash_set
.PHONY : raw_hash_set

# fast build rule for target.
raw_hash_set/fast:
	$(MAKE) -f absl/container/CMakeFiles/raw_hash_set.dir/build.make absl/container/CMakeFiles/raw_hash_set.dir/build
.PHONY : raw_hash_set/fast

#=============================================================================
# Target rules for targets named stacktrace

# Build rule for target.
stacktrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stacktrace
.PHONY : stacktrace

# fast build rule for target.
stacktrace/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/stacktrace.dir/build.make absl/debugging/CMakeFiles/stacktrace.dir/build
.PHONY : stacktrace/fast

#=============================================================================
# Target rules for targets named symbolize

# Build rule for target.
symbolize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symbolize
.PHONY : symbolize

# fast build rule for target.
symbolize/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/symbolize.dir/build.make absl/debugging/CMakeFiles/symbolize.dir/build
.PHONY : symbolize/fast

#=============================================================================
# Target rules for targets named leak_check_disable

# Build rule for target.
leak_check_disable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leak_check_disable
.PHONY : leak_check_disable

# fast build rule for target.
leak_check_disable/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/leak_check_disable.dir/build.make absl/debugging/CMakeFiles/leak_check_disable.dir/build
.PHONY : leak_check_disable/fast

#=============================================================================
# Target rules for targets named failure_signal_handler

# Build rule for target.
failure_signal_handler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 failure_signal_handler
.PHONY : failure_signal_handler

# fast build rule for target.
failure_signal_handler/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/failure_signal_handler.dir/build.make absl/debugging/CMakeFiles/failure_signal_handler.dir/build
.PHONY : failure_signal_handler/fast

#=============================================================================
# Target rules for targets named debugging_internal

# Build rule for target.
debugging_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debugging_internal
.PHONY : debugging_internal

# fast build rule for target.
debugging_internal/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/debugging_internal.dir/build.make absl/debugging/CMakeFiles/debugging_internal.dir/build
.PHONY : debugging_internal/fast

#=============================================================================
# Target rules for targets named examine_stack

# Build rule for target.
examine_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examine_stack
.PHONY : examine_stack

# fast build rule for target.
examine_stack/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/examine_stack.dir/build.make absl/debugging/CMakeFiles/examine_stack.dir/build
.PHONY : examine_stack/fast

#=============================================================================
# Target rules for targets named demangle_internal

# Build rule for target.
demangle_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demangle_internal
.PHONY : demangle_internal

# fast build rule for target.
demangle_internal/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/demangle_internal.dir/build.make absl/debugging/CMakeFiles/demangle_internal.dir/build
.PHONY : demangle_internal/fast

#=============================================================================
# Target rules for targets named leak_check

# Build rule for target.
leak_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leak_check
.PHONY : leak_check

# fast build rule for target.
leak_check/fast:
	$(MAKE) -f absl/debugging/CMakeFiles/leak_check.dir/build.make absl/debugging/CMakeFiles/leak_check.dir/build
.PHONY : leak_check/fast

#=============================================================================
# Target rules for targets named city

# Build rule for target.
city: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 city
.PHONY : city

# fast build rule for target.
city/fast:
	$(MAKE) -f absl/hash/CMakeFiles/city.dir/build.make absl/hash/CMakeFiles/city.dir/build
.PHONY : city/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) -f absl/hash/CMakeFiles/hash.dir/build.make absl/hash/CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named int128

# Build rule for target.
int128: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 int128
.PHONY : int128

# fast build rule for target.
int128/fast:
	$(MAKE) -f absl/numeric/CMakeFiles/int128.dir/build.make absl/numeric/CMakeFiles/int128.dir/build
.PHONY : int128/fast

#=============================================================================
# Target rules for targets named str_format_internal

# Build rule for target.
str_format_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 str_format_internal
.PHONY : str_format_internal

# fast build rule for target.
str_format_internal/fast:
	$(MAKE) -f absl/strings/CMakeFiles/str_format_internal.dir/build.make absl/strings/CMakeFiles/str_format_internal.dir/build
.PHONY : str_format_internal/fast

#=============================================================================
# Target rules for targets named strings_internal

# Build rule for target.
strings_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strings_internal
.PHONY : strings_internal

# fast build rule for target.
strings_internal/fast:
	$(MAKE) -f absl/strings/CMakeFiles/strings_internal.dir/build.make absl/strings/CMakeFiles/strings_internal.dir/build
.PHONY : strings_internal/fast

#=============================================================================
# Target rules for targets named strings

# Build rule for target.
strings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strings
.PHONY : strings

# fast build rule for target.
strings/fast:
	$(MAKE) -f absl/strings/CMakeFiles/strings.dir/build.make absl/strings/CMakeFiles/strings.dir/build
.PHONY : strings/fast

#=============================================================================
# Target rules for targets named synchronization

# Build rule for target.
synchronization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synchronization
.PHONY : synchronization

# fast build rule for target.
synchronization/fast:
	$(MAKE) -f absl/synchronization/CMakeFiles/synchronization.dir/build.make absl/synchronization/CMakeFiles/synchronization.dir/build
.PHONY : synchronization/fast

#=============================================================================
# Target rules for targets named graphcycles_internal

# Build rule for target.
graphcycles_internal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphcycles_internal
.PHONY : graphcycles_internal

# fast build rule for target.
graphcycles_internal/fast:
	$(MAKE) -f absl/synchronization/CMakeFiles/graphcycles_internal.dir/build.make absl/synchronization/CMakeFiles/graphcycles_internal.dir/build
.PHONY : graphcycles_internal/fast

#=============================================================================
# Target rules for targets named time_zone

# Build rule for target.
time_zone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time_zone
.PHONY : time_zone

# fast build rule for target.
time_zone/fast:
	$(MAKE) -f absl/time/CMakeFiles/time_zone.dir/build.make absl/time/CMakeFiles/time_zone.dir/build
.PHONY : time_zone/fast

#=============================================================================
# Target rules for targets named time

# Build rule for target.
time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time
.PHONY : time

# fast build rule for target.
time/fast:
	$(MAKE) -f absl/time/CMakeFiles/time.dir/build.make absl/time/CMakeFiles/time.dir/build
.PHONY : time/fast

#=============================================================================
# Target rules for targets named bad_any_cast_impl

# Build rule for target.
bad_any_cast_impl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bad_any_cast_impl
.PHONY : bad_any_cast_impl

# fast build rule for target.
bad_any_cast_impl/fast:
	$(MAKE) -f absl/types/CMakeFiles/bad_any_cast_impl.dir/build.make absl/types/CMakeFiles/bad_any_cast_impl.dir/build
.PHONY : bad_any_cast_impl/fast

#=============================================================================
# Target rules for targets named bad_optional_access

# Build rule for target.
bad_optional_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bad_optional_access
.PHONY : bad_optional_access

# fast build rule for target.
bad_optional_access/fast:
	$(MAKE) -f absl/types/CMakeFiles/bad_optional_access.dir/build.make absl/types/CMakeFiles/bad_optional_access.dir/build
.PHONY : bad_optional_access/fast

#=============================================================================
# Target rules for targets named bad_variant_access

# Build rule for target.
bad_variant_access: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bad_variant_access
.PHONY : bad_variant_access

# fast build rule for target.
bad_variant_access/fast:
	$(MAKE) -f absl/types/CMakeFiles/bad_variant_access.dir/build.make absl/types/CMakeFiles/bad_variant_access.dir/build
.PHONY : bad_variant_access/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... raw_logging_internal"
	@echo "... spinlock_wait"
	@echo "... base"
	@echo "... dynamic_annotations"
	@echo "... malloc_internal"
	@echo "... throw_delegate"
	@echo "... raw_hash_set"
	@echo "... stacktrace"
	@echo "... symbolize"
	@echo "... leak_check_disable"
	@echo "... failure_signal_handler"
	@echo "... debugging_internal"
	@echo "... examine_stack"
	@echo "... demangle_internal"
	@echo "... leak_check"
	@echo "... city"
	@echo "... hash"
	@echo "... int128"
	@echo "... str_format_internal"
	@echo "... strings_internal"
	@echo "... strings"
	@echo "... synchronization"
	@echo "... graphcycles_internal"
	@echo "... time_zone"
	@echo "... time"
	@echo "... bad_any_cast_impl"
	@echo "... bad_optional_access"
	@echo "... bad_variant_access"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

